name: Build python package and release it on GitHub and PyPI

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies for building and releasing
        run: python -m pip install build twine
      - name: Build package
        run: python -m build
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
      - name: Release on PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
